
"use client";

import { motion, AnimatePresence } from "framer-motion";
import { X, Shield, FileText } from "lucide-react";

interface LegalModalProps {
    isOpen: boolean;
    onClose: () => void;
    type: "privacy" | "terms";
}

export const LegalModal = ({ isOpen, onClose, type }: LegalModalProps) => {
    const isPrivacy = type === "privacy";

    const content = isPrivacy ? {
        title: "Privacy Policy",
        icon: Shield,
        sections: [
            {
                heading: "Data Collection",
                text: "We collect minimal information required to provide you with the best voice-to-web experience. This includes your voice input (processed in real-time) and account details if you sign up."
            },
            {
                heading: "Speech Processing",
                text: "Voice commands are processed locally in your browser whenever possible. When necessary for advanced generation, data is sent securely to our encrypted AI partners like Google Gemini."
            },
            {
                heading: "Security",
                text: "Your designs and account data are stored in secure, production-grade cloud environments with strict access controls and end-to-end encryption."
            }
        ]
    } : {
        title: "Terms of Service",
        icon: FileText,
        sections: [
            {
                heading: "Usage Agreement",
                text: "By using Voice Web, you agree to use the tool for personal or professional design purposes. Misuse of the voice interface or automated scraping is prohibited."
            },
            {
                heading: "Ownership",
                text: "You own the designs you generate. Voice Web provides the layout and code, which you are free to export and use in your own projects."
            },
            {
                heading: "Limitations",
                text: "Voice Web is provided 'as is'. While we strive for perfection, we are not responsible for any design inaccuracies or code errors generated by the AI."
            }
        ]
    };

    return (
        <AnimatePresence>
            {isOpen && (
                <div className="fixed inset-0 z-[200] flex items-center justify-center p-4 pointer-events-auto">
                    {/* Backdrop */}
                    <motion.div
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        onClick={onClose}
                        className="absolute inset-0 bg-brand-background/80 backdrop-blur-md"
                    />

                    {/* Modal */}
                    <motion.div
                        initial={{ opacity: 0, scale: 0.95, y: 20 }}
                        animate={{ opacity: 1, scale: 1, y: 0 }}
                        exit={{ opacity: 0, scale: 0.95, y: 20 }}
                        className="relative w-full max-w-2xl bg-brand-card border border-brand-border rounded-[2.5rem] p-10 mt-10 shadow-2xl overflow-hidden max-h-[85vh] overflow-y-auto custom-scrollbar"
                    >
                        {/* Glow effect */}
                        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-64 h-64 bg-brand-accent/10 blur-3xl rounded-full" />

                        <div className="relative z-10">
                            <div className="flex items-center gap-4 mb-8">
                                <div className="w-12 h-12 bg-brand-accent/10 rounded-2xl flex items-center justify-center text-brand-accent border border-brand-accent/20">
                                    <content.icon className="w-6 h-6" />
                                </div>
                                <h3 className="text-3xl font-bold text-brand-foreground tracking-tight">{content.title}</h3>
                            </div>

                            <div className="space-y-8">
                                {content.sections.map((section, i) => (
                                    <div key={i} className="space-y-3">
                                        <h4 className="text-lg font-bold text-brand-foreground/80">{section.heading}</h4>
                                        <p className="text-brand-foreground/40 leading-relaxed">
                                            {section.text}
                                        </p>
                                    </div>
                                ))}
                            </div>

                            <button
                                onClick={onClose}
                                className="w-full mt-10 py-4 bg-brand-foreground/5 border border-brand-border rounded-2xl font-bold text-brand-foreground hover:bg-brand-foreground/10 transition-all active:scale-95"
                            >
                                Close
                            </button>
                        </div>

                        {/* Close button icon */}
                        <button
                            onClick={onClose}
                            className="absolute top-8 right-8 p-2 rounded-full bg-brand-foreground/5 text-brand-foreground/40 hover:text-brand-foreground hover:bg-brand-foreground/10 transition-all"
                        >
                            <X className="w-4 h-4" />
                        </button>
                    </motion.div>
                </div >
            )}
        </AnimatePresence >
    );
};
